name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
prerelease: true
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "debt"
  - title: "🛠 Dependency Updates"
    labels:
      - "dependencies"
  - title: "⚙️ GitOps"
    labels:
      - "git-ops"
      - "ci-cd"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "major"
      - "breaking"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES
